//
//  SKID_GLOBALS.h
//  Skid
//
//  Created by Brad Allred on 11/28/11.
//  Copyright (c) 2011 For Every Body. All rights reserved.
//

#ifndef Skid_SKID_GLOBALS_h
#define Skid_SKID_GLOBALS_h

#import <Foundation/Foundation.h>

//function key codes
#define SKID_KEY_F1		122
#define SKID_KEY_F2		120
#define SKID_KEY_F3		99
#define SKID_KEY_F4		118
#define SKID_KEY_F5		96
#define SKID_KEY_F6		97
#define SKID_KEY_F7		98
#define SKID_KEY_F8		100
#define SKID_KEY_F9		101
#define SKID_KEY_F10	109
#define SKID_KEY_F11	103
#define SKID_KEY_F12	111

// first 2 bytes of data1 field values for NSSystemDefined events generated by Fkeys
#define SKID_EV_DATA_F1 @"0x0003" //Brightness down
#define SKID_EV_DATA_F2 @"0x0002" //Brightness up
//skip F3 & F4. they are "standard" key events
#define SKID_EV_DATA_F5 @"0x0016" //brightness down
#define SKID_EV_DATA_F6 @"0x0015" //brightness up
#define SKID_EV_DATA_F7 @"0x0014" //skip back
#define SKID_EV_DATA_F8 @"0x0010" //play/pause
#define SKID_EV_DATA_F9 @"0x0013" //skip ahead
#define SKID_EV_DATA_F10 @"0x0007" //mute
#define SKID_EV_DATA_F11 @"0x0001" //vol down
#define SKID_EV_DATA_F12 @"0x0000" //vol up

//special key codes
#define SKID_KEY_EXPOSE				160 //F3
#define SKID_KEY_DASHBOARD			130 //F4
#define SKID_KEY_BRIGHTNESS_DOWN	144 //F5
#define SKID_KEY_BRIGHTNESS_UP		145 //F6

#define SKID_LEFT_MOUSE		0x0001
#define SKID_RIGHT_MOSUE	0x0010
#define SKID_OTHER_MOUSE	0xFFFC

#define SKID_AGENT_NAME @"SkidAgent"
#define SKID_DOMAIN @"edu.uvu.skid"

#pragma mark macros
#define N(X) [NSNumber numberWithInt:X]
#define S(X) [NSString stringWithFormat:@"0x%04X", X]

#pragma mark typedefs
typedef NSUInteger MouseButtonFlags;

#endif
